AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AnonymousSlackbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app/src/index.default
      Runtime: nodejs12.x
      CodeUri: .
      Events:
        AnonymousSlackBotApi:
          Type: Api
          Properties:
            Path: /
            Method: POST
